# Generated by Django 5.0.3 on 2024-03-14 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_created_at_task_deleted_task_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='task',
            name='deleted_at',
        ),
    ]
