# Generated by Django 5.0.3 on 2024-03-14 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_remove_task_deleted_remove_task_deleted_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
