# Generated by Django 5.0.3 on 2024-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_created_at_task_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='created',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='updated',
            new_name='fecha_modificacion',
        ),
        migrations.AddField(
            model_name='task',
            name='fecha_baja',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
