# Generated by Django 5.0.3 on 2024-03-14 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_created_task_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='fecha_creacion',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='fecha_modificacion',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='fecha_baja',
        ),
        migrations.AddField(
            model_name='task',
            name='ok',
            field=models.BooleanField(default=False),
        ),
    ]
