# Generated by Django 5.0.3 on 2024-03-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_rename_fecha_creacion_task_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='ok',
            new_name='deleted',
        ),
    ]
